BigMarkets = {
    "LAL": ["lakers", "lal"],
    "NY": ["knicks", "new york", "ny", "nyknicks"],
    "CHI": ["bulls", "chicago", "chi", "chicagobulls"],
    "PHI": ["76ers", "seventysixers", "philadelphia", "phila", "phi"],
    "DAL": ["mavericks", "mavs", "dallas", "dal", "dallasmavericks"],
    "ATL": ["hawks", "atlanta", "atl", "atlantahawks"],
    "BOS": ["celtics", "boston", "bos", "bostonceltics"],
    "GSW": ["gsw", "goldenstatewarriors", "goldenstate", "warriors", "dubs", "dubsnation"],
    "TOR": ["raptors", "toronto", "tor", "torontoraptors"],
    "HOU": ["houston", "rockets", "hou", "houstonrockets"],
    "WSH": ["washington", "wizards", "wsh", "washingtonwizards"],
    "PHX": ["phoenix", "suns", "phx", "phoenixsuns"],
}

MediumMarkets = {
    "MIN": ["minnesota", "timberwolves", "min", "wolves", "minnesotatimberwolves"],
    "DET": ["detroit", "pistons", "det", "detroitpistons"],
    "DEN": ["denver", "nuggets", "den", "denvernuggets"],
    "ORL": ["orlando", "magic", "orl", "orlandomagic"],
    "MIA": ["miami", "heat", "mia", "miamiheat"],
    "CLE": ["cleveland", "cavaliers", "cle", "clevelandcavaliers", "cavs"],
}


SmallMarkets = {
    "MEM": ["memphis", "grizzlies", "mem", "memphisgrizzlies"],
    "NO": ["pelicans", "pels", "neworleans", "neworleanspelicans", "nola"],
    "OKC": ["okc", "oklahomacitythunder", "oklahoma", "thunders"],
    "MIL": ["bucks", "milwaukee", "mil", "milwaukeebucks"],
    "SA": ["spurs", "sanantoniospurs", "sanantonio", "sa", "sas"],
    "UTAH": ["utahjazz", "utah", "jazz"],
    "IND": ["pacers", "indiana", "indi", "ind", "indianapacers"],
    "CHA": ["charlotte", "hornets", "cha", "charlottehornets"],
    "POR": ["trailblazers", "portlandtrailblazers", "blazers", "portland", "por"],
    "SAC": ["sacramento", "kings", "sac", "sacramentokings"],
}


Correspondence = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "New Orleans Hornets": "NO",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GS",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Lakers": "LAL",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New York Knicks": "NY",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SA",
    "Oklahoma City Thunder": "OKC",
    "Utah Jazz": "UTAH",
    "Washington Wizards": "WSH",
    "Toronto Raptors": "TOR",
    "Memphis Grizzlies": "MEM",
    "Charlotte Bobcats": "CHA",
    "New Orleans Pelicans": "NO",
    "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA",
}
